version: '3'
services:
  snapserver:
    build:
      context: ../.
      dockerfile: DockerfileServerRPI
      args:
        SNAPCASTVERSION: 0.26.0

  snapclient:
    build:
      context: ../.
      dockerfile: DockerfileClientRPI
      args:
        SNAPCASTVERSION: 0.26.0
    links:
     - snapserver:snapserverhost
    devices:
     - "/dev/snd/:/dev/snd/"
    command: "-h snapserverhost"
